name: MonsterBox
main: net.betterverse.monsterbox.MonsterBox
version: 1.0
author: aPunch
commands:
  mbox:
    description: Various monster spawner commands.
       
permissions:
  monsterbox.*:
    default: op
    children:
      monsterbox.set: true
      monsterbox.spawn.*:
        children:
          monsterbox.spawn.pig: true
          monsterbox.spawn.chicken: true
          monsterbox.spawn.cow: true
          monsterbox.spawn.sheep: true
          monsterbox.spawn.squid: true
          monsterbox.spawn.creeper: true
          monsterbox.spawn.ghast: true
          monsterbox.spawn.pigzombie: true
          monsterbox.spawn.skeleton: true
          monsterbox.spawn.spider: true
          monsterbox.spawn.zombie: true
          monsterbox.spawn.slime: true
          monsterbox.spawn.monster: true
          monsterbox.spawn.giant: true
          monsterbox.spawn.wolf: true
          monsterbox.spawn.cavespider: true
          monsterbox.spawn.enderman: true
          monsterbox.spawn.silverfish: true
          monsterbox.spawn.enderdragon: true
          monsterbox.spawn.villager: true
          monsterbox.spawn.blaze: true
          monsterbox.spawn.mushroomcow: true
          monsterbox.spawn.magmacube: true
          monsterbox.spawn.snowman: true  