name: MonsterBox
main: net.betterverse.monsterbox.MonsterBox
version: 1.0
author: aPunch
commands:
  mbox:
    description: Various monster seter commands.
       
permissions:
  monsterbox.*:
    default: op
    children:
      monsterbox.break: true
      monsterbox.set.*:
        children:
          monsterbox.set: true
          monsterbox.set.pig: true
          monsterbox.set.chicken: true
          monsterbox.set.cow: true
          monsterbox.set.sheep: true
          monsterbox.set.squid: true
          monsterbox.set.creeper: true
          monsterbox.set.ghast: true
          monsterbox.set.pigzombie: true
          monsterbox.set.skeleton: true
          monsterbox.set.spider: true
          monsterbox.set.zombie: true
          monsterbox.set.slime: true
          monsterbox.set.monster: true
          monsterbox.set.giant: true
          monsterbox.set.wolf: true
          monsterbox.set.cavespider: true
          monsterbox.set.enderman: true
          monsterbox.set.silverfish: true
          monsterbox.set.enderdragon: true
          monsterbox.set.villager: true
          monsterbox.set.blaze: true
          monsterbox.set.mushroomcow: true
          monsterbox.set.magmacube: true
          monsterbox.set.snowman: true  