name: SpawnerBox
main: net.betterverse.spawnerbox.SpawnerBox
version: 1.0
author: aPunch
commands:
  sb:
    description: Various SpawnerBox commands.
       
permissions:
  spawnerbox.*:
    default: op
    children:
      spawnerbox.break: true
      spawnerbox.set.*:
        children:
          spawnerbox.set: true
          spawnerbox.set.pig: true
          spawnerbox.set.chicken: true
          spawnerbox.set.cow: true
          spawnerbox.set.sheep: true
          spawnerbox.set.squid: true
          spawnerbox.set.creeper: true
          spawnerbox.set.ghast: true
          spawnerbox.set.pigzombie: true
          spawnerbox.set.skeleton: true
          spawnerbox.set.spider: true
          spawnerbox.set.zombie: true
          spawnerbox.set.slime: true
          spawnerbox.set.monster: true
          spawnerbox.set.giant: true
          spawnerbox.set.wolf: true
          spawnerbox.set.cavespider: true
          spawnerbox.set.enderman: true
          spawnerbox.set.silverfish: true
          spawnerbox.set.enderdragon: true
          spawnerbox.set.villager: true
          spawnerbox.set.blaze: true
          spawnerbox.set.mushroomcow: true
          spawnerbox.set.magmacube: true
          spawnerbox.set.snowman: true  